//PARTNER NOTES. FROM RUBRIC NEED TO COMPLETE:

// /profile (with messages)
// Unauthenticated Users should be able to:

// See a list of all posts [X]
// Sign up for an account with username and password [X]
// Sign in with correct username/password combination [X]
// Unauthenticated Users should not be able to:

// Create a new post [X]
// Delete any post [X]
// Send a message to the author of any post [X]

// Authenticated Users should be able to:

// Create a new post [X]
// Delete a post for which they are the author [X]
// Send a message to the author of any post for which they are not the author [X]
// See all messages for any post for which they are the author [DOES NOT WORK YET]
// See all messages they've received in a special view [DOES NOT WORK YET]

// Authenticated Users should not be able to:

// Delete posts for which they are not the author [X]
// Send a message to themselves [X]

// All users should be able to:

// Filter posts with a simple text matcher (no fetch call needed here) [DOES NOT WORK YET]
// Opportunity for EXTRA CREDIT of up to 5% added to your overall score. Authenticated Users would be delighted to be able to:

// Edit a post for which they are the author [DOES NOT WORK BUT EXTRA CREDIT IF NOT ENOUGH TIME]
