//NOTES FOR TEACHER:
// - search function did not work, but when the code is struck in on search.jsx the console log should return whatever
// letters are placed into the search bar, we think this is an important feature for the search bar.
//-For edit we knew to change the method to PATCH, we made a route to singlepost from the edit button that would have been nice
// to render the specific post you clicked edit on and have a form to input those edits and return you to posts page.

// /profile (with messages)
// Unauthenticated Users should be able to:

// See a list of all posts [X]
// Sign up for an account with username and password [X]
// Sign in with correct username/password combination [X]
// Unauthenticated Users should not be able to:

// Create a new post [X]
// Delete any post [X]
// Send a message to the author of any post [X]

// Authenticated Users should be able to:

// Create a new post [X]
// Delete a post for which they are the author [X]
// Send a message to the author of any post for which they are not the author [X]
// See all messages for any post for which they are the author [X]
// See all messages they've received in a special view [X]

// Authenticated Users should not be able to:

// Delete posts for which they are not the author [X]
// Send a message to themselves [X]

// All users should be able to:

// Filter posts with a simple text matcher (no fetch call needed here) [DOES NOT WORK YET]
// Opportunity for EXTRA CREDIT of up to 5% added to your overall score. Authenticated Users would be delighted to be able to:

// Edit a post for which they are the author [DOES NOT WORK BUT EXTRA CREDIT IF NOT ENOUGH TIME]
